name: Flask Aplication

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Primero nos logueamos usando tu Secret GHCR_PATH Y AJAM
    - name: Login en GitHub Container Registry
      run: echo "${{ secrets.GHCR_PATH }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    # 2. Construimos la imagen y le asignamos los DOS tags exigidos (1.0.0 y latest)
    - name: Construir imagen de docker
      run: |
        docker build -t ghcr.io/ljbtorres-debug/holataller:2.0.0 .
        docker tag ghcr.io/ljbtorres-debug/holataller:2.0.0 ghcr.io/ljbtorres-debug/holataller:latest
    
    # 3. Subimos ambos tags a GHCR
    - name: Publicar la imagen creada.
      run: |
        docker push ghcr.io/ljbtorres-debug/holataller:2.0.0
        docker push ghcr.io/ljbtorres-debug/holataller:latest